# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('message', models.TextField(verbose_name='message')),
                ('is_processed', models.BooleanField(verbose_name='is processed')),
            ],
            options={
                'verbose_name_plural': 'leads',
                'verbose_name': 'lead',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=255, verbose_name='decription')),
                ('is_tested', models.BooleanField(default=True, verbose_name='is tested')),
                ('category', models.CharField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C')], max_length=1, verbose_name='category')),
                ('sku', models.PositiveIntegerField(blank=True, null=True, verbose_name='SKU')),
            ],
            options={
                'verbose_name_plural': 'nomenclature',
                'verbose_name': 'nomenclature',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=255, verbose_name='decription')),
                ('is_cover', models.BooleanField(verbose_name='is cover')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yet_another_site.Nomenclature', verbose_name='nomenclature')),
            ],
            options={
                'verbose_name_plural': 'pictures',
                'verbose_name': 'picture',
            },
        ),
    ]
