# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import yet_another_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('yet_another_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(default=0, upload_to=yet_another_site.models.picture_directory_path, verbose_name='image'),
            preserve_default=False,
        ),
    ]
