# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yet_another_site', '0003_auto_20170415_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cover_for', to='yet_another_site.Picture', verbose_name='cover'),
        ),
    ]
