# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yet_another_site', '0004_auto_20170415_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='is_processed',
        ),
    ]
